### ISSUE TITLE
请求添加文档说明

### ISSUE THREAD

**Issue by liang-hiwin** [yaotthaha/cdns#1]
这个源码好像是mosdns的重构版，但是缺少使用文档，配置中有些插件描述好像少了点什么

**Comment by yaotthaha** [comment]
想法参考mosdns，源码自己手撸的，有部分搬mosdns的

文档后面会完善

**Comment by liang-hiwin** [comment]
> 想法参考mosdns，源码自己手撸的，有部分搬mosdns的
> 
> 文档后面会完善
好的，redis在举例的配置中没描述是否支持unix协议，
同理listen能否添加支持unix协议

**Comment by yaotthaha** [comment]
暂时不支持，下个小版本v0.0.2会支持

**Comment by liang-hiwin** [comment]
后期能安排下面几个功能？

1、blackhole: 能丢弃应答，生成空应答，或者生成包含特定 IP 应答。用于屏蔽请求。
包含下面几个：
_drop_response: 丢弃已存在的应答。
_new_empty_response: 生成 Rcode 为 0 的空应答。放入“请求上下文”。(模拟域名存在但没有所请求类型的记录)
_new_servfail_response: 生成 Rcode 为 2 (SERVFAIL: 服务器失败)应答。放入“请求上下文”。
_new_nxdomain_response: 生成 Rcode 为 3 (NXDOMAIN: 域名不存在)应答。放入“请求上下文”。

2、ttl: 修改应答的 TTL。
3、bufsize: 修改请求的 EDNS0 的 UDP Size。防止 UDP 碎片。
4、bootstrap: 手动指定用于解析 addr 中域名的 bootstrap 服务器。

要求有点多，sorry

**Comment by yaotthaha** [comment]
这些后面会考虑加

**Comment by liang-hiwin** [comment]
> 这些后面会考虑加

大佬牛掰

**Comment by yaotthaha** [comment]
```

workflow:
  - tag: test
    rules:
      - exec:
          - return: SUCCESS # 生成 Rcode 为 0 的空应答
          - return: FAIL # 生成 Rcode 为 2 (SERVFAIL: 服务器失败)应答
          - return: NXDOMAIN # 生成 Rcode 为 3 (NXDOMAIN: 域名不存在)应答
      
      - exec:
          - set-ttl: 86400 # 修改应答的 TTL，单位：秒

upstreams:
  - tag: ali-dns
    type: tls
    options:
      address: dns.alidns.com
      idle-timeout: 10s
      query-timeout: 2s
      bootstrap: # 若 address 包含域名，则必须设置 Bootstrap
        upstream: basic-dns # 查询域名的上游服务器
        strategy: ipv4-only # 域名查询策略，ipv4-prefer|ipv4-only|ipv6-prefer|ipv6-only

  - tag: basic-dns
    type: tcp
    options:
      address: 223.5.5.5
      idle-timeout: 10s
      query-timeout: 2s
```
