### ISSUE TITLE
请求增加上游服务可以合并在一起写

### ISSUE THREAD

**Issue by liang-hiwin** [yaotthaha/cdns#2]
比如
```
  - tag: Google-HTTPS-DNS
    type: https
    options:
      address: 8.8.8.8
      connect-timeout: 3s
      idle-timeout: 10s
      query-timeout: 800ms
     
      address: 8.8.4.4
      connect-timeout: 3s
      idle-timeout: 10s
      query-timeout: 800ms

      path: /dns-query
      header:
        Host: dns.google
      enable-h3: false

      tls:
        # TLS 字段
      bootstrap:
        # Bootstrap 字段
      dialer:
        # Dialer 字段


```
